[package]
name = "reprise-fixtures"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
reprise-geom.workspace = true
reprise-compose.workspace = true
reprise-doc.workspace = true
reprise-font.workspace = true
reprise-layout.workspace = true
reprise-plugin.workspace = true

[dev-dependencies]
reprise-edit.workspace = true
reprise-diag.workspace = true
reprise-display.workspace = true
insta.workspace = true
serde_json.workspace = true
wat.workspace = true
