"""Generate orientation_table.rs from the Unicode Character Database.

    python generate_orientation.py VerticalOrientation-17.0.0.txt > orientation_table.rs

Input: https://www.unicode.org/Public/17.0.0/ucd/VerticalOrientation.txt, SHA-256
dcef09c3fb24d356b042569c328ec341efc5b53447700d799f2fb4834c3cd3cd. The table
lists every range whose value is not R, the file's @missing default, with
adjacent ranges of one value merged. A unit test checks it against ICU4X.
"""

import hashlib
import sys

VALUES = {"U": "Upright", "Tu": "TransformedUpright", "Tr": "TransformedRotated"}


def main(path):
    data = open(path, "rb").read()
    lines = data.decode("utf-8").splitlines()
    version = lines[0].strip("# ").removeprefix("VerticalOrientation-").removesuffix(".txt")
    ranges = []
    for line in lines:
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        cps, value = (part.strip() for part in body.split(";"))
        lo, _, hi = cps.partition("..")
        lo = int(lo, 16)
        hi = int(hi, 16) if hi else lo
        if value == "R":
            continue
        ranges.append((lo, hi, value))
    ranges.sort()
    merged = []
    for lo, hi, value in ranges:
        if merged and merged[-1][2] == value and merged[-1][1] + 1 == lo:
            merged[-1] = (merged[-1][0], hi, value)
        else:
            merged.append((lo, hi, value))
    out = sys.stdout
    out.write("// Generated by generate_orientation.py from VerticalOrientation-%s.txt\n" % version)
    out.write("// (SHA-256 %s). Do not edit.\n\n" % hashlib.sha256(data).hexdigest())
    out.write("use super::VerticalOrientation::{self, *};\n\n")
    out.write('pub(super) const UNICODE_VERSION: &str = "%s";\n\n' % version)
    out.write("/// Ranges whose value is not `Rotated`, sorted and disjoint.\n")
    out.write("#[rustfmt::skip]\n")
    out.write("pub(super) const RANGES: &[(u32, u32, VerticalOrientation)] = &[\n")
    for lo, hi, value in merged:
        out.write("    (0x%04X, 0x%04X, %s),\n" % (lo, hi, VALUES[value]))
    out.write("];\n")


if __name__ == "__main__":
    main(sys.argv[1])
