[package]
name = "reprise-shape"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
reprise-geom.workspace = true
reprise-text.workspace = true
reprise-font.workspace = true
reprise-diag.workspace = true
harfrust.workspace = true
icu_properties.workspace = true
icu_segmenter.workspace = true
unicode-bidi.workspace = true
serde.workspace = true
