[package]
name = "reprise-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "reprise"
path = "src/main.rs"

[dependencies]
reprise-layout.workspace = true
reprise-display.workspace = true
reprise-fixtures.workspace = true

[dev-dependencies]
reprise-doc.workspace = true
insta.workspace = true
