/* tslint:disable */
/* eslint-disable */
// Generated by cargo run -p reprise --example generate_types. Do not edit.
export type Payload<T> = { version: number, data: T, };
export type Bytes = { bytes: Uint8Array, };
export type Severity = "info" | "warning" | "error";
export type Diagnostic = { code: string, severity: Severity, message: string, subject: string | null, start: number | null, end: number | null, };
export type ErrorPayload = { code: string, severity: Severity, message: string, command: number | null, };
export type Create = { document_id: string, peer_id: string, };
export type Open = { peer_id: string, };
export type State = { document_id: string, peer_id: string, revision: Array<Clock>, can_undo: boolean, can_redo: boolean, blocks: Array<Block>, diagnostics: Array<Diagnostic>, };
export type Clock = { peer: string, counter: number, };
export type Block = { id: string, parent: string | null, kind: BlockKind, text: string, };
export type BlockKind = "paragraph" | "annotation";
export type Style = { families: Array<string> | null, size: string | null, line_height: string | null, };
export type Command = { "kind": "add-relation", relation: Relation, } | { "kind": "remove-relation", id: string, } | { "kind": "insert-text", node: string, at: number, text: string, } | { "kind": "delete-text", node: string, start: number, end: number, } | { "kind": "split-block", node: string, at: number, } | { "kind": "join-blocks", first: string, second: string, } | { "kind": "insert-block", parent: string | null, index: number, block_kind: BlockKind, text: string, style: Style, } | { "kind": "delete-block", node: string, } | { "kind": "move-block", node: string, parent: string | null, index: number, } | { "kind": "set-style", node: string, style: Style, };
export type Transaction = { commands: Array<Command>, };
export type Effect = { "kind": "text", node: string, at: number, removed: number, inserted: number, } | { "kind": "split", node: string, at: number, new: string, } | { "kind": "join", first: string, second: string, at: number, } | { "kind": "deleted", node: string, };
export type Applied = { blocks: Array<string>, relations: Array<string>, effects: Array<Effect>, diagnostics: Array<Diagnostic>, };
export type FontStyle = "normal" | "italic" | "oblique";
export type FontDeclaration = { family: string, weight: number, style: FontStyle, stretch: number, face_index: number, };
export type Face = { family: string, hash: string, };
export type AssetDeclaration = { id: string, kind: AssetKind, };
export type AssetKind = "image" | "other";
export type LayoutOptions = { width: number, height: number, max_pages: number, viewport_start: number, viewport_end: number, };
export type LayoutToken = { document_id: string, revision: Array<Clock>, generation: string, };
export type Pass = "flow" | "region-feedback" | "relations" | "reading-order" | "complete";
export type LayoutProgress = { token: LayoutToken, used: number, pass: Pass, viewport_ready: boolean, complete: boolean, settled: boolean, outside_document: boolean, pages: Array<number>, counters: Counters, };
export type Counters = { units: number, shapes: number, compositions: number, reused_compositions: number, };
export type Affinity = "upstream" | "downstream";
export type Caret = { node: string, offset: number, affinity: Affinity, };
export type Cursor = { caret: Caret, goal_x: number | null, };
export type Movement = "next-grapheme" | "previous-grapheme" | "next-word" | "previous-word" | "visual-right" | "visual-left" | "inline-forward" | "inline-backward" | "line-up" | "line-down" | "line-start" | "line-end" | "line-leftmost" | "line-rightmost" | "line-inline-start" | "line-inline-end" | "block-start" | "block-end" | "document-start" | "document-end";
export type Move = { cursor: Cursor, movement: Movement, };
export type Selection = { anchor: Caret, focus: Caret, };
export type Rect = { x: number, y: number, width: number, height: number, };
export type PageRect = { page: number, rect: Rect, };
export type HitTest = { page: number, x: number, y: number, };
export type Hit = { caret: Caret, page: number, inside: boolean, };
export type ReadingStep = { node: string, line: number, page: number, };
export type ExportFormat = "plain-text" | "html" | "native" | "pdf";
export type Loss = { code: string, disposition: Disposition, detail: string, };
export type Disposition = "preserved" | "approximated" | "dropped";
export type Exported = { content: Bytes, losses: Array<Loss>, diagnostics: Array<Diagnostic>, };
export type Paste = { at: Caret | null, };
export type TextImport = { text: string, html: boolean, at: Caret | null, };
export type SyncInfo = { document_id: string, peer_id: string, vector: Array<Clock>, };
export type SyncUpdate = { document_id: string, from_peer: string, vector: Array<Clock>, content: Bytes, };
export type Awareness = { document_id: string, peer_id: string, content: Bytes, };
export type Capability = "read-text" | "insert-text";
export type PluginPhase = "layout" | "editing";
export type Dimension = "length" | "number" | "percentage" | "ratio";
export type PluginFunction = { name: string, operation: number, params: Array<Dimension>, variadic: Dimension | null, returns: Dimension, };
export type PluginSpec = { name: string, plugin_version: string, sha256: string, phase: PluginPhase, imports: Array<Capability>, grants: Array<Capability>, functions: Array<PluginFunction>, fuel: number, memory_pages: number, table_elements: number, buffer_bytes: number, };
export type PluginInstall = { "kind": "relation", schema: RelationSchema, operation: number, } | { "kind": "functions" } | { "kind": "geometry", operation: number, };
export type PluginEdit = { operation: number, nodes: Array<string>, };
export type Point = { x: number, y: number, };
export type Matrix = { xx: number, yx: number, xy: number, yy: number, tx: number, ty: number, };
export type Layer = "content" | "debug";
export type ByteRange = { start: number, end: number, };
export type Glyph = { id: number, x: number, y: number, text: ByteRange, };
export type GlyphRun = { face: Face, size: number, color: [number, number, number, number], text: string, glyphs: Array<Glyph>, layer: Layer, };
export type Segment = { "move": Point } | { "line": Point } | { "quad": [Point, Point] } | { "cubic": [Point, Point, Point] } | "close";
export type Stroke = { color: [number, number, number, number], width: number, };
export type DisplayItem = { "type": "glyphs" } & GlyphRun | { "type": "path", path: Array<Segment>, fill: [number, number, number, number] | null, stroke: Stroke | null, layer: Layer, } | { "type": "group", transform: Matrix, clip: Array<Segment> | null, items: Array<DisplayItem>, };
export type DisplayList = { width: number, height: number, items: Array<DisplayItem>, };
export type DisplayPage = { token: LayoutToken, page: number, settled: boolean, complete: boolean, display: DisplayList, };
export type Relation = { schema: string, owner: string | null, targets: { [key in string]: Array<Target> }, params: { [key in string]: Param }, };
export type Target = { "node": string } | { "range": string } | { "structural": StructuralQuery } | { "layout": LayoutQuery } | { "snapshot": SnapshotReference };
export type StructuralQuery = { "query": "next-sibling", from: string, kind: BlockKind | null, } | { "query": "previous-sibling", from: string, kind: BlockKind | null, } | { "query": "nth-child", of: string | null, index: number, from_end: boolean, kind: BlockKind | null, } | { "query": "first-child", of: string | null, kind: BlockKind | null, } | { "query": "last-child", of: string | null, kind: BlockKind | null, } | { "query": "parent", of: string, } | { "query": "children", of: string | null, kind: BlockKind | null, };
export type LayoutQuery = { "query": "line-containing", range: string, } | { "query": "previous-line", range: string, } | { "query": "next-line", range: string, } | { "query": "first-line", node: string, } | { "query": "last-line", node: string, } | { "query": "lines-in", range: string, } | { "query": "frame-containing", range: string, } | { "query": "page-containing", range: string, };
export type SnapshotReference = { revision: Array<Clock>, of: SnapshotSubject, };
export type SnapshotSubject = { "node": string } | { "range": string };
export type Param = { "length": RelativeLength } | { "int": string } | { "bool": boolean } | { "text": string };
export type RelativeLength = { "pt": number } | { "em": number };
export type TargetClass = "node" | "range" | "structural" | "layout" | "snapshot";
export type ParamKind = "length" | "int" | "bool" | "text";
export type Ownership = "owned" | "independent";
export type OnTargetDeleted = "rebind" | "keep-missing" | "delete";
export type CopyInside = "duplicate" | "drop";
export type CopyCrossing = "keep-outside" | "drop";
export type CopyPolicy = { inside: CopyInside, crossing: CopyCrossing, };
export type RoleSpec = { name: string, accepts: Array<TargetClass>, min: number, max: number | null, };
export type ParamSpec = { name: string, kind: ParamKind, required: boolean, };
export type RelationSchema = { id: string, version: number, ownership: Ownership, roles: Array<RoleSpec>, params: Array<ParamSpec>, on_target_deleted: OnTargetDeleted, on_copy: CopyPolicy, };
export type CopyAs = { selection: Selection, format: CopyFormat, };
export type Resource = { id: string, kind: ResourceKind, hash: string, available: boolean, font: Face | null, location: ResourceLocation | null, };
export type ResourceKind = "font" | "image" | "other";
export type ResourceLocation = { "kind": "path", "value": string } | { "kind": "url", "value": string };
export type CopyFormat = "plain-text" | "html";



export class DocumentSession {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    apply(request: Payload<Transaction>): Payload<Applied>;
    awareness(content: Uint8Array): Payload<Awareness>;
    cancel(job: number): Payload<boolean>;
    caret_rect(request: Payload<Caret>): Payload<PageRect>;
    copy(request: Payload<Selection>): Payload<Bytes>;
    copy_as(request: Payload<CopyAs>): Payload<Exported>;
    declare_font(request: Payload<FontDeclaration>, content: Uint8Array): Payload<Face>;
    diagnostics(): Payload<Array<Diagnostic>>;
    display_json(page: number): Payload<string>;
    display_page(page: number): Payload<DisplayPage>;
    export(request: Payload<ExportFormat>): Payload<Exported>;
    export_updates(): Payload<SyncUpdate>;
    hit_test(request: Payload<HitTest>): Payload<Hit>;
    import_text(request: Payload<TextImport>): Payload<Applied>;
    import_updates(request: Payload<SyncUpdate>): Payload<SyncInfo>;
    install_plugin(plugin: number, request: Payload<PluginInstall>): Payload<boolean>;
    load_plugin(request: Payload<PluginSpec>, content: Uint8Array): Payload<number>;
    move_cursor(request: Payload<Move>): Payload<Cursor>;
    partial_page(job: number, page: number): Payload<DisplayPage>;
    paste(request: Payload<Paste>, content: Uint8Array): Payload<Applied>;
    png(page: number, scale_permille: number): Payload<Bytes>;
    reading_order(): Payload<Array<ReadingStep>>;
    redo(): Payload<boolean>;
    register_asset(request: Payload<AssetDeclaration>, content: Uint8Array): Payload<string>;
    release_job(job: number): Payload<boolean>;
    release_plugin(plugin: number): Payload<boolean>;
    resource_bytes(request: Payload<string>): Payload<Bytes>;
    resources(): Payload<Array<Resource>>;
    run_plugin_edit(plugin: number, request: Payload<PluginEdit>, content: Uint8Array): Payload<Applied>;
    save(): Payload<Bytes>;
    selection_rects(request: Payload<Selection>): Payload<Array<PageRect>>;
    start_layout(request: Payload<LayoutOptions>): Payload<number>;
    state(): Payload<State>;
    step(job: number, budget: number): Payload<LayoutProgress>;
    svg(page: number): Payload<string>;
    sync_info(): Payload<SyncInfo>;
    undo(): Payload<boolean>;
    validate_awareness(request: Payload<Awareness>): Payload<Bytes>;
}

export class Workspace {
    free(): void;
    [Symbol.dispose](): void;
    create(request: Payload<Create>): DocumentSession;
    constructor();
    open(request: Payload<Open>, content: Uint8Array): DocumentSession;
}

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_documentsession_free: (a: number, b: number) => void;
    readonly __wbg_workspace_free: (a: number, b: number) => void;
    readonly documentsession_apply: (a: number, b: any) => [number, number, number];
    readonly documentsession_awareness: (a: number, b: any) => [number, number, number];
    readonly documentsession_cancel: (a: number, b: number) => [number, number, number];
    readonly documentsession_caret_rect: (a: number, b: any) => [number, number, number];
    readonly documentsession_copy: (a: number, b: any) => [number, number, number];
    readonly documentsession_copy_as: (a: number, b: any) => [number, number, number];
    readonly documentsession_declare_font: (a: number, b: any, c: any) => [number, number, number];
    readonly documentsession_diagnostics: (a: number) => [number, number, number];
    readonly documentsession_display_json: (a: number, b: number) => [number, number, number];
    readonly documentsession_display_page: (a: number, b: number) => [number, number, number];
    readonly documentsession_export: (a: number, b: any) => [number, number, number];
    readonly documentsession_export_updates: (a: number) => [number, number, number];
    readonly documentsession_hit_test: (a: number, b: any) => [number, number, number];
    readonly documentsession_import_text: (a: number, b: any) => [number, number, number];
    readonly documentsession_import_updates: (a: number, b: any) => [number, number, number];
    readonly documentsession_install_plugin: (a: number, b: number, c: any) => [number, number, number];
    readonly documentsession_load_plugin: (a: number, b: any, c: any) => [number, number, number];
    readonly documentsession_move_cursor: (a: number, b: any) => [number, number, number];
    readonly documentsession_partial_page: (a: number, b: number, c: number) => [number, number, number];
    readonly documentsession_paste: (a: number, b: any, c: any) => [number, number, number];
    readonly documentsession_png: (a: number, b: number, c: number) => [number, number, number];
    readonly documentsession_reading_order: (a: number) => [number, number, number];
    readonly documentsession_redo: (a: number) => [number, number, number];
    readonly documentsession_register_asset: (a: number, b: any, c: any) => [number, number, number];
    readonly documentsession_release_job: (a: number, b: number) => [number, number, number];
    readonly documentsession_release_plugin: (a: number, b: number) => [number, number, number];
    readonly documentsession_resource_bytes: (a: number, b: any) => [number, number, number];
    readonly documentsession_resources: (a: number) => [number, number, number];
    readonly documentsession_run_plugin_edit: (a: number, b: number, c: any, d: any) => [number, number, number];
    readonly documentsession_save: (a: number) => [number, number, number];
    readonly documentsession_selection_rects: (a: number, b: any) => [number, number, number];
    readonly documentsession_start_layout: (a: number, b: any) => [number, number, number];
    readonly documentsession_state: (a: number) => [number, number, number];
    readonly documentsession_step: (a: number, b: number, c: number) => [number, number, number];
    readonly documentsession_svg: (a: number, b: number) => [number, number, number];
    readonly documentsession_sync_info: (a: number) => [number, number, number];
    readonly documentsession_undo: (a: number) => [number, number, number];
    readonly documentsession_validate_awareness: (a: number, b: any) => [number, number, number];
    readonly workspace_create: (a: number, b: any) => [number, number, number];
    readonly workspace_new: () => number;
    readonly workspace_open: (a: number, b: any, c: any) => [number, number, number];
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
