// Run after generating the Node package: node ts/smoke.cjs <pkg-dir>
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const wasm = require(path.resolve(process.argv[2], "reprise_wasm.js"));
const p = data => ({ version: 1, data });
const ws = new wasm.Workspace();
const doc = ws.create(p({ document_id: "00112233445566778899aabbccddeeff", peer_id: "1" }));
const inserted = doc.apply(p({ commands: [{ kind: "insert-block", parent: null, index: 0, block_kind: "paragraph", text: "office ffi אבג", style: { families: ["Source Serif Pro", "serif"], size: null, line_height: null } }] }));
const node = inserted.data.blocks[0];
const options = p({ width: 420 * 1024, height: 300 * 1024, max_pages: 1000, viewport_start: 0, viewport_end: 1 });
function finish(doc) { const job = doc.start_layout(options).data; for (let i = 0; i < 10_000; i++) { const progress = doc.step(job, 1); if (progress.data.complete) { doc.release_job(job); return; } } throw new Error("explicit smoke job bound exceeded"); }
finish(doc);
assert.equal(doc.display_json(0).data, fs.readFileSync(path.join(__dirname, "../../reprise/tests/display.json"), "utf8").trimEnd());
assert.throws(() => doc.apply({ version: 99, data: {} }), e => e.version === 1 && e.data.code === "bindings.version");
assert.throws(() => doc.apply(p({ commands: [{ kind: "insert-text", node: "invalid", at: 0, text: "bad" }] })), e => e.data.code === "bindings.id");
const cyc = p({ commands: [] }); cyc.data.extra = cyc;
assert.throws(() => doc.apply(cyc), e => e.data.code === "bindings.invalid");
const caret = { node, offset: 0, affinity: "downstream" };
assert.deepEqual(doc.selection_rects(p({ anchor: caret, focus: caret })).data, []);
const selection = p({ anchor: caret, focus: { node, offset: Buffer.byteLength("office ffi אבג"), affinity: "upstream" } });
const clip = doc.copy(selection).data.bytes;
assert.ok(clip instanceof Uint8Array);
doc.paste(p({ at: null }), clip); doc.undo(); finish(doc);
const saved = doc.save().data.bytes;
assert.ok(saved instanceof Uint8Array);
const second = ws.open(p({ peer_id: "2" }), saved); finish(second);
assert.equal(second.display_json(0).data, doc.display_json(0).data);
const before = doc.start_layout(options).data;
doc.apply(p({ commands: [{ kind: "insert-text", node, at: 0, text: "A" }] }));
assert.throws(() => doc.step(before, 1), e => e.data.code === "bindings.stale");doc.release_job(before);
second.import_updates(doc.export_updates());
finish(doc);finish(second);assert.equal(doc.display_json(0).data, second.display_json(0).data);
assert.ok(doc.export(p("pdf")).data.content.bytes instanceof Uint8Array);
assert.ok(doc.png(0, 1000).data.bytes instanceof Uint8Array);
assert.ok(doc.awareness(new Uint8Array([0, 255])).data.content.bytes instanceof Uint8Array);
assert.throws(() => doc.awareness("wrong byte type"), e => e.data.code === "bindings.invalid");
let reads = 0;
const getterRequest = p({ get commands() { reads++; return []; } });
doc.apply(getterRequest); assert.equal(reads, 1);
const throwing = p({ get commands() { throw new Error("getter"); } });
assert.throws(() => doc.apply(throwing), e => e.data.code === "bindings.invalid");
const deep = p({ commands: [] }); let deepAt = deep.data; for (let i = 0; i < 66; i++) deepAt = deepAt.extra = {};
assert.throws(() => doc.apply(deep), e => e.data.code === "bindings.limit");
const moduleBytes = new Uint8Array(fs.readFileSync(path.join(__dirname, "../../plugin/test-plugins/demo.wasm")));
const crypto = require("node:crypto");
const plugin = doc.load_plugin(p({ name: "demo", plugin_version: "1", sha256: crypto.createHash("sha256").update(moduleBytes).digest("hex"), phase: "layout", imports: [], grants: [], functions: [{ name: "demo-double", operation: 1, params: ["length"], variadic: null, returns: "length" }], fuel: 100000, memory_pages: 16, table_elements: 1024, buffer_bytes: 65536 }), moduleBytes).data;
doc.install_plugin(plugin, p({ kind: "functions" }));
doc.install_plugin(plugin, p({ kind: "geometry", operation: 2 }));
doc.apply(p({ commands: [{ kind: "set-style", node, style: { families: null, size: "demo-double(6pt)", line_height: null } }] }));
finish(doc);
assert.ok(!doc.diagnostics().data.some(note => note.code === "style.function-failed" || note.code === "plugin.trap"));
// Default style needs neither a family chain nor host font registration.
const defaultDoc = ws.create(p({ document_id: "10112233445566778899aabbccddeeff", peer_id: "21" }));
const defaultNode = defaultDoc.apply(p({ commands: [{ kind: "insert-block", parent: null, index: 0, block_kind: "paragraph", text: "office ffi café אבג مرحبا é", style: { families: null, size: null, line_height: null } }] })).data.blocks[0];
finish(defaultDoc);
assert.ok(defaultDoc.diagnostics().data.every(note => note.severity === "info"));
assert.ok(defaultDoc.copy(p({ anchor: { node: defaultNode, offset: 0, affinity: "downstream" }, focus: { node: defaultNode, offset: 6, affinity: "upstream" } })).data.bytes instanceof Uint8Array);
const imageDoc = ws.create(p({ document_id: "20112233445566778899aabbccddeeff", peer_id: "22" }));
const red = new Uint8Array(fs.readFileSync(path.join(__dirname, "../../../fixtures/images/red-1x1.png")));
const asset = imageDoc.register_asset(p({ id: "red", kind: "image" }), red).data;
const image = { at: null, asset, alt: "A red café image", width: 20 * 1024, height: 20 * 1024, style: { families: null, size: null, line_height: null } };
const imageNode = imageDoc.apply(p({ commands: [{ kind: "insert-image", image }] })).data.blocks[0];
finish(imageDoc);
const drawing = imageDoc.display_json(0).data;
assert.equal(drawing, fs.readFileSync(path.join(__dirname, "../../reprise/tests/images.json"), "utf8").trimEnd());
assert.ok(drawing.includes('"type":"image"') && drawing.includes(asset));
assert.ok(imageDoc.diagnostics().data.every(note => note.severity === "info"));
const vector = imageDoc.svg(0).data;
assert.ok(vector.includes("data:image/png;base64,"));
const raster = imageDoc.png(0, 1000).data.bytes;
const pdfImage = imageDoc.export(p("pdf"));
assert.ok(pdfImage.data.content.bytes instanceof Uint8Array);
assert.equal(pdfImage.data.losses.find(loss => loss.code === "export.assets").disposition, "preserved");
const imageCopy = imageDoc.copy(p({ anchor: { node: imageNode, offset: 0, affinity: "downstream" }, focus: { node: imageNode, offset: Buffer.byteLength(image.alt), affinity: "upstream" } })).data.bytes;
const imageTarget = ws.create(p({ document_id: "30112233445566778899aabbccddeeff", peer_id: "23" }));
imageTarget.paste(p({ at: null }), imageCopy); finish(imageTarget);
assert.equal(imageTarget.svg(0).data, vector);
assert.deepEqual(imageTarget.png(0, 1000).data.bytes, raster);
imageTarget.undo(); assert.equal(imageTarget.state().data.blocks.length, 0); imageTarget.redo(); finish(imageTarget);
const imageOpen = ws.open(p({ peer_id: "24" }), imageTarget.save().data.bytes); finish(imageOpen);
assert.equal(imageOpen.display_json(0).data, drawing);
assert.equal(imageOpen.svg(0).data, vector);
assert.deepEqual(imageOpen.png(0, 1000).data.bytes, raster);
const missingDoc = ws.create(p({ document_id: "40112233445566778899aabbccddeeff", peer_id: "25" }));
missingDoc.insert_image(p(image)); finish(missingDoc);
assert.notDeepEqual(missingDoc.png(0, 1000).data.bytes, raster);
missingDoc.free(); imageOpen.free(); imageTarget.free(); imageDoc.free(); defaultDoc.free();
// Collaboration (format 2): byte parity with the native golden, deltas,
// refusals, the anchored selection and presence.
const DOC = "00112233445566778899aabbccddeeff";
const pa = ws.create(p({ document_id: DOC, peer_id: "1" }));
const pNode = pa.apply(p({ commands: [{ kind: "insert-block", parent: null, index: 0, block_kind: "paragraph", text: "parity", style: { families: null, size: null, line_height: null } }] })).data.blocks[0];
pa.apply(p({ commands: [{ kind: "insert-text", node: pNode, at: 6, text: " אב" }] }));
const golden = pa.sync_export(p({ since: [] })).data;
assert.equal(Buffer.from(golden.content.bytes).toString("hex"), fs.readFileSync(path.join(__dirname, "../../reprise/tests/sync_delta.hex"), "utf8").trim());
assert.ok(golden.content.bytes instanceof Uint8Array && golden.kind === "delta" && golden.format === 2);
const pb = ws.create(p({ document_id: DOC, peer_id: "2" }));
pb.sync_import(p(golden));
assert.deepEqual(pb.state().data.blocks, pa.state().data.blocks);
pa.set_selection(p({ anchor: { node: pNode, offset: 0, affinity: "downstream" }, focus: { node: pNode, offset: 6, affinity: "upstream" } }));
pb.apply(p({ commands: [{ kind: "insert-text", node: pNode, at: 0, text: ">> " }] }));
const report = pa.sync_import(pb.sync_export(p({ since: pa.sync_info().data.vector }))).data;
assert.ok(report.changed && report.changes.blocks.includes(pNode));
assert.equal(report.selection.anchor.offset, 3);
const v = pa.sync_info().data.vector;
pb.apply(p({ commands: [{ kind: "insert-text", node: pNode, at: 0, text: "1" }] }));
const one = pb.sync_export(p({ since: v }));
pb.apply(p({ commands: [{ kind: "insert-text", node: pNode, at: 0, text: "2" }] }));
const two = pb.sync_export(p({ since: one.data.vector }));
assert.throws(() => pa.sync_import(two), e => e.data.code === "sync.missing");
pa.sync_import(one); pa.sync_import(two);
assert.deepEqual(pa.state().data.blocks, pb.state().data.blocks);
const undone = pa.undo_report().data;
assert.ok(undone.changed && undone.selection !== null);
assert.ok(pa.redo_report().data.changed);
pb.sync_import(pa.sync_export(p({ since: pb.sync_info().data.vector })));
const presence = pa.presence(p({ selection: { anchor: { node: pNode, offset: 0, affinity: "downstream" }, focus: { node: pNode, offset: 2, affinity: "upstream" } }, meta: { name: "Ada" } }));
finish(pb);
const view = pb.resolve_presence(presence).data;
assert.equal(view.meta.name, "Ada"); assert.ok(view.caret && view.rects.length > 0);
const garbage = pb.resolve_presence(p({ document_id: DOC, peer_id: "1", content: { bytes: new Uint8Array([1, 2, 3]) } })).data;
assert.equal(garbage.selection, null);
const stable = pa.anchor_selection(p({ anchor: { node: pNode, offset: 1, affinity: "downstream" }, focus: { node: pNode, offset: 1, affinity: "downstream" } }));
assert.equal(pb.resolve_selection(stable).data.anchor.offset, 1);
pa.free(); pb.free();
second.free();doc.free();ws.free();
console.log("WASM smoke: native JSON and sync byte parity, editor loop, sync, collaboration, defaults, images, bytes, and hostile objects passed");
