// Run after generating the Node package: node ts/smoke.cjs <pkg-dir>
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const wasm = require(path.resolve(process.argv[2], "reprise_wasm.js"));
const p = data => ({ version: 1, data });
const ws = new wasm.Workspace();
const doc = ws.create(p({ document_id: "00112233445566778899aabbccddeeff", peer_id: "1" }));
const inserted = doc.apply(p({ commands: [{ kind: "insert-block", parent: null, index: 0, block_kind: "paragraph", text: "office ffi אבג", style: { families: ["Source Serif Pro", "serif"], size: null, line_height: null } }] }));
const node = inserted.data.blocks[0];
const options = p({ width: 420 * 1024, height: 300 * 1024, max_pages: 1000, viewport_start: 0, viewport_end: 1 });
function finish(doc) { const job = doc.start_layout(options).data; for (let i = 0; i < 10_000; i++) { const progress = doc.step(job, 1); if (progress.data.complete) { doc.release_job(job); return; } } throw new Error("explicit smoke job bound exceeded"); }
finish(doc);
assert.equal(doc.display_json(0).data, fs.readFileSync(path.join(__dirname, "../../reprise/tests/display.json"), "utf8").trimEnd());
assert.throws(() => doc.apply({ version: 99, data: {} }), e => e.version === 1 && e.data.code === "bindings.version");
assert.throws(() => doc.apply(p({ commands: [{ kind: "insert-text", node: "invalid", at: 0, text: "bad" }] })), e => e.data.code === "bindings.id");
const cyc = p({ commands: [] }); cyc.data.extra = cyc;
assert.throws(() => doc.apply(cyc), e => e.data.code === "bindings.invalid");
const caret = { node, offset: 0, affinity: "downstream" };
assert.deepEqual(doc.selection_rects(p({ anchor: caret, focus: caret })).data, []);
const selection = p({ anchor: caret, focus: { node, offset: Buffer.byteLength("office ffi אבג"), affinity: "upstream" } });
const clip = doc.copy(selection).data.bytes;
assert.ok(clip instanceof Uint8Array);
doc.paste(p({ at: null }), clip); doc.undo(); finish(doc);
const saved = doc.save().data.bytes;
assert.ok(saved instanceof Uint8Array);
const second = ws.open(p({ peer_id: "2" }), saved); finish(second);
assert.equal(second.display_json(0).data, doc.display_json(0).data);
const before = doc.start_layout(options).data;
doc.apply(p({ commands: [{ kind: "insert-text", node, at: 0, text: "A" }] }));
assert.throws(() => doc.step(before, 1), e => e.data.code === "bindings.stale");doc.release_job(before);
second.import_updates(doc.export_updates());
finish(doc);finish(second);assert.equal(doc.display_json(0).data, second.display_json(0).data);
assert.ok(doc.export(p("pdf")).data.content.bytes instanceof Uint8Array);
assert.ok(doc.png(0, 1000).data.bytes instanceof Uint8Array);
assert.ok(doc.awareness(new Uint8Array([0, 255])).data.content.bytes instanceof Uint8Array);
assert.throws(() => doc.awareness("wrong byte type"), e => e.data.code === "bindings.invalid");
let reads = 0;
const getterRequest = p({ get commands() { reads++; return []; } });
doc.apply(getterRequest); assert.equal(reads, 1);
const throwing = p({ get commands() { throw new Error("getter"); } });
assert.throws(() => doc.apply(throwing), e => e.data.code === "bindings.invalid");
const deep = p({ commands: [] }); let deepAt = deep.data; for (let i = 0; i < 66; i++) deepAt = deepAt.extra = {};
assert.throws(() => doc.apply(deep), e => e.data.code === "bindings.limit");
const moduleBytes = new Uint8Array(fs.readFileSync(path.join(__dirname, "../../plugin/test-plugins/demo.wasm")));
const crypto = require("node:crypto");
const plugin = doc.load_plugin(p({ name: "demo", plugin_version: "1", sha256: crypto.createHash("sha256").update(moduleBytes).digest("hex"), phase: "layout", imports: [], grants: [], functions: [{ name: "demo-double", operation: 1, params: ["length"], variadic: null, returns: "length" }], fuel: 100000, memory_pages: 16, table_elements: 1024, buffer_bytes: 65536 }), moduleBytes).data;
doc.install_plugin(plugin, p({ kind: "functions" }));
doc.install_plugin(plugin, p({ kind: "geometry", operation: 2 }));
doc.apply(p({ commands: [{ kind: "set-style", node, style: { families: null, size: "demo-double(6pt)", line_height: null } }] }));
finish(doc);
assert.ok(!doc.diagnostics().data.some(note => note.code === "style.function-failed" || note.code === "plugin.trap"));
second.free();doc.free();ws.free();
console.log("WASM smoke: native JSON parity, editor loop, sync, bytes, and hostile objects passed");
